---
title: "Bike Share Analysis"
author: "Matthew Coudert"
date: "Saturday September 26th"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Downloading Packages Needed
```{r packages}
library(tidyverse)
library(ggplot2)
library(lubridate)
```

## Saving datasets
```{r datasets}
washington_dataset <- read_csv("BikeWashingtonDC.csv")
seoul_dataset <- read_csv("BikeSeoul.csv")
```

## Seoul dataset clean up
```{r seoul_dataset}
seoul_dataset <- seoul_dataset %>%
  select(-c('Visibility (10m)','Dew point temperature(C)','Solar Radiation (MJ/m2)','Rainfall(mm)','Snowfall (cm)','Functioning Day')) %>% 
  filter(!is.na('Rented Bike Count')) %>%
  rename(Date = 'Date',Count = 'Rented Bike Count',Hour = 'Hour', Temperature = 'Temperature(C)', Humidity = 'Humidity(%)', WindSpeed = 'Wind speed (m/s)', Season = 'Seasons', Holiday = 'Holiday') %>%
  mutate(Date = parse_date_time(Date,"dmy")) %>%
  mutate(FullDate = make_datetime(year = year(Date), month = month(Date), day = day(Date), hour = Hour)) %>%
  select(-c(Date,Hour)) %>%
  mutate(Holiday = factor(ifelse(Holiday == "Holiday", "Yes", "No"), levels = c("Yes","No"))) %>%
  mutate(Season = ordered(Season, levels = c("Spring","Summer","Autumn","Winter"))) %>%
  print()
```

## Washington DC dataset clean up
```{r washington_dataset}
washington_dataset <- washington_dataset %>%
  select(c('dteday','cnt','hr','temp','hum','windspeed','season','holiday')) %>%
  rename(Date = 'dteday', Count = 'cnt', Hour = 'hr', Temperature = 'temp', Humidity = 'hum', WindSpeed = 'windspeed', Season = 'season', Holiday = 'holiday') %>%
  mutate(Humidity = Humidity*100) %>%
  mutate(Temperature = Temperature*(39-(-8))+(-8)) %>%
  mutate(WindSpeed = WindSpeed*67*1000/60^2) %>%
  mutate(Season = ifelse(Season == 1, "Winter", Season)) %>%
  mutate(Season = ifelse(Season == 2, "Spring", Season)) %>%
  mutate(Season = ifelse(Season == 3, "Summer", Season)) %>%
  mutate(Season = ifelse(Season == 4, "Autumn", Season)) %>%
  mutate(Season = ordered(Season, levels = c("Spring","Summer","Autumn","Winter"))) %>%
  mutate(Holiday = factor(ifelse(Holiday == 1, "Yes", "No"), levels = c("Yes","No"))) %>%
  mutate(Date = parse_date_time(Date,"ymd")) %>%
  mutate(FullDate = make_datetime(year = year(Date), month = month(Date), day = day(Date), hour = Hour)) %>%
  select(-c(Date,Hour)) %>%
  print()
```


## Creating big dataset with both Seoul and Washington DC
```{r big_dataset}
seoul_dataset <- seoul_dataset %>%
  mutate(City = "Seoul")
washington_dataset <- washington_dataset %>%
  mutate(City = "Washington DC")
dataset <- seoul_dataset %>%
  add_row(washington_dataset) %>%
  arrange(Count)
```


## Temperature v Day Plot
```{r temp_v_day}
temp_plot <- dataset %>%
  ggplot(aes(x = yday(FullDate), y = Temperature)) + 
  geom_point() + 
  xlab("Day of year from January 1st") +
  ylab("Temperature (C)")+
  stat_smooth(data = dataset, mapping = aes(x = yday(FullDate), y = Temperature)) +
  facet_wrap(~City, scales = "free") +
  ggtitle("Temperature over the year in Washington DC and Seoul")
temp_plot
```

## Plotting season v bike demand
```{r season_v_bike_demand}
season_plot_hour <- dataset %>%
  ggplot(aes(x = Season, y = Count)) +
  geom_boxplot() + 
  facet_wrap(~City, scales = "free") + 
  ggtitle("Boxplot of Season versus number of Bikes Rented") +
  xlab("Season") + 
  ylab("Number of bikes rented per hour")
season_plot_hour
season_plot_day <- dataset %>%
  group_by(date(FullDate),City, Season) %>%
  summarise(DayCount = sum(Count)) %>%
  ggplot(aes(x = Season, y = DayCount)) +
  geom_boxplot() + 
  facet_wrap(~City, scales = "free") + 
  ggtitle("Boxplot of Season versus number of Bikes Rented per Day") +
  xlab("Season") +
  ylab("Number of bikes rented per day") 
season_plot_day
```

## Plotting holiday v bike demand
```{r holiday_v_bike_demand}
holiday_plot <- dataset %>%
  group_by(date(FullDate), City, Holiday) %>%
  summarise(DayCount = sum(Count)) %>%
  ggplot(aes(x = Holiday, y = DayCount)) +
  geom_boxplot() +
  facet_wrap(~City, scales = "free") +
  ggtitle("Boxplot of Holiday versus number of Bikes rented per day") +
  xlab("Holiday") +
  ylab("Number of bikes rented per day")
holiday_plot
```

## Plotting weather variables v bike demand
```{r weather_v_bike_demand}
air_temp_plot <- dataset %>%
  ggplot(aes(x = Temperature, y = Count)) +
  geom_point() +
  facet_wrap(~City, scale = "free") +
  stat_smooth(data = dataset, mapping = aes(x = Temperature, y = Count)) +
  ggtitle("Temperature vs Bike Rental") +
  ylab("Number of bikes hired per hour")
air_temp_plot

humidity_plot <- dataset %>%
  ggplot(aes(x = Humidity, y = Count)) +
  geom_point() +
  facet_wrap(~City, scale = "free") +
  stat_smooth(data = dataset, mapping = aes(x = Humidity, y = Count)) +
  ggtitle("Humidity vs Bike Rental") +
  ylab("Number of bikes hired per hour")
humidity_plot

wind_plot <- dataset %>%
  ggplot(aes(x = WindSpeed, y = Count)) +
  geom_point() +
  facet_wrap(~City, scale = "free") +
  stat_smooth(data = dataset, mapping = aes(x = WindSpeed, y = Count)) +
  ggtitle("WindSpeed (m/s) vs Bike Rental") +
  ylab("Number of bikes hired per hour")
wind_plot
```


## STATISTICAL MODELLING

## Linear Model for Seoul
```{r linear_seoul}
seoul_model_dataset <- seoul_dataset %>%
  mutate(Winter = ifelse(Season == "Winter", 1, 0)) %>%
  mutate(Spring = ifelse(Season == "Spring", 1, 0)) %>%
  mutate(Summer = ifelse(Season == "Summer", 1, 0)) %>%
  mutate(Autumn = ifelse(Season == "Autumn", 1, 0))


seoul_model <- lm(formula = Count ~ Winter + Spring + Summer + Temperature + Humidity + WindSpeed, data = seoul_model_dataset)
summary(seoul_model)

```

